---
  - name: set hostname
    hostname: name={{ hostname }}

  - name: Change network files
    shell: sed -i "s/HOSTNAME=.*/HOSTNAME={{ hostname }}/g" /etc/sysconfig/network

  - name: Stop Iptables
    service: name=iptables state=stopped  enabled=no

  - name: disable seliunx
    shell: /usr/sbin/setenforce 0  && sed -i 's/SELINUX=enforcing/SELINUX=disabled/g' /etc/sysconfig/selinux

  - name: Install libselinux-python
    raw: yum install libselinux-python -y 

  - name: copy epel yum source
    copy: src={{ item.src }}  dest={{ item.dest }} owner=root group=root mode=644
    with_items:
         - {src: epel.repo, dest: /etc/yum.repos.d/epel.repo }
         - {src: RPM-GPG-KEY-EPEL-6, dest: /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-6 }
         - {src: RPM-GPG-KEY-ZABBIX, dest: /etc/pki/rpm-gpg/RPM-GPG-KEY-ZABBIX }
         - {src: zabbix.repo, dest: /etc/yum.repos.d/zabbix.repo }
  - name: copy /etc/hosts files
    template: src=hosts.j2 dest=/etc/hosts owner=root group=root mode=644
